language: go
sudo: false
go:
  - 1.7
  - 1.8
  - 1.9

install:
  - go get golang.org/x/tools/cmd/cover github.com/mattn/goveralls

script:
  - go test ./integration_test/
  - go test -coverprofile=.coverprofile .
  - goveralls -coverprofile=.coverprofile -service=travis-ci -repotoken $COVERALLS_API_TOKEN
