language: go
os: linux
go:
  - "1.11"
  - "1.12"
  - "1.13"

install:
  - go get golang.org/x/tools/cmd/cover github.com/mattn/goveralls
  # install golangci-lint to ./bin
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v1.22.2

script:
  - ./bin/golangci-lint run ./...
  - go test -tags=integration -coverprofile=.coverprofile .
  - goveralls -coverprofile=.coverprofile -service=travis-ci -repotoken $COVERALLS_API_TOKEN

jobs:
  include:
    - stage: trigger downstream
      jdk: oraclejdk8
      script: |
        echo "TRAVIS_BRANCH=$TRAVIS_BRANCH TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST"
        if [[ ($TRAVIS_BRANCH == master) &&
              ($TRAVIS_PULL_REQUEST == false) ]] ; then
          curl -LO --retry 3 https://raw.github.com/mernst/plume-lib/master/bin/trigger-travis.sh
          sh trigger-travis.sh blockloop scan_integration_tests $TRAVIS_ACCESS_TOKEN
        fi
